name: student_planner
description: University Student Timetable & Study Planner App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  icalendar_parser: ^2.0.0
  shared_preferences: ^2.2.2
  uuid: ^4.2.2
  collection: ^1.18.0
  file_picker: ^5.2.7
  http: ^1.2.0
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  flutter_polyline_points: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
